apiVersion: v1
kind: Namespace
metadata:
  name: time-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-api
  namespace: time-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-api
  template:
    metadata:
      labels:
        app: time-api
    spec:
      containers:
        - name: time-api
          image: gcr.io/${project_id}/time-api:${image_tag}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: time-api
  namespace: time-api
spec:
  selector:
    app: time-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: time-api
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-api-ingress
  namespace: time-api
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: time-api
                port:
                  number: 80
