apiVersion: v1
kind: Namespace
metadata:
  name: time-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-api
  namespace: time-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-api
  template:
    metadata:
      labels:
        app: time-api
    spec:
      serviceAccountName: time-api-sa
      containers:
        - name: time-api
          image: gcr.io/$(PROJECT_ID)/time-api:$(GITHUB_SHA)
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 75m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: GCP_PROJECT_ID
              value: $(PROJECT_ID)
            - name: IMAGE_TAG
              value: $(GITHUB_SHA)
---
apiVersion: v1
kind: Service
metadata:
  name: time-api
  namespace: time-api
spec:
  selector:
    app: time-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: time-api
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-time-api
  namespace: time-api
spec:
  podSelector:
    matchLabels:
      app: time-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-api-ingress
  namespace: time-api
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "time-api-ingress-ip"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: time-api
                port:
                  number: 80
